### ISSUE TITLE
Align gpfdist sink with GPDB5

### ISSUE THREAD

**Issue by tzolov** [spring-cloud-stream-app-starters/gpfdist#8]
`GPDB 5` doesn't support external error tables anymore: https://gpdb.docs.pivotal.io/500/relnotes/GPDB_500_README.html#topic_nyg_nv4_l1b

To be compliant with GPDB5 the `LOG ERROS INTO error_table` clause has to be replaced by just `LOG ERRORS`. 

Note: this change will be also backward compatible with GPDB4

**Comment by jvalkeal** [comment]
Fixed extra space problem with integration tests.
Squashed/merged per https://github.com/spring-cloud-stream-app-starters/gpfdist/commit/7cf5d58aa97b1684371642325b5e38d0c7e1f8d4.
